# Generated by Django 5.1.4 on 2025-08-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lote_auditable', models.BooleanField(blank=True, default=True, null=True)),
                ('costo_produccion', models.FloatField(blank=True, null=True)),
                ('existencia', models.FloatField(blank=True, null=True)),
                ('cantidad_remitida', models.FloatField(blank=True, null=True)),
                ('cantidad_recibida', models.FloatField(blank=True, null=True)),
                ('cantidad_inicial', models.FloatField(blank=True, null=True)),
                ('cantidad_actual', models.FloatField(blank=True, null=True)),
                ('alta', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AlmacenBar', to='bussiness.stockalmacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductoBarStock', to='bussiness.producto')),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BarStock', to='bussiness.puntoventa')),
                ('transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TransferenciaBar', to='bussiness.transferencia')),
                ('transformacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductoTransformadoBar', to='bussiness.transformacion')),
            ],
        ),
    ]
