# Generated by Django 5.1.4 on 2025-03-17 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bussiness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosElaboracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('monto', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NotaCocina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cocina_id', models.TextField(blank=True, null=True)),
                ('cocina_nombre', models.TextField(blank=True, null=True)),
                ('cocinero_nombre', models.TextField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CantidadSubproducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(default=0.0)),
                ('subgrupo', models.CharField(blank=True, max_length=5, null=True)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedidaSubproducto', to='bussiness.medida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CantidadSubproducto', to='bussiness.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Cocina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('direccion', models.TextField()),
                ('codigo', models.TextField()),                
                ('activo', models.BooleanField(default=True)),
                ('porciento_cocinero', models.FloatField(default=0.0)),
                ('pago_fijo_cocinero', models.FloatField(default=0.0)),
                ('pago_fijo_ayudante', models.FloatField(default=0.0)),
                ('puntos_venta', models.ManyToManyField(related_name='puntos_venta_cocina', to='bussiness.puntoventa')),
                ('users_access', models.ManyToManyField(related_name='users_access_cocina', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuadre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recibido', models.FloatField(default=0.0)),
                ('entregado', models.FloatField(blank=True, default=0.0, null=True)),
                ('usado', models.FloatField(blank=True, default=0.0, null=True)),
                ('bajas', models.FloatField(blank=True, default=0.0, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CuadreProducto', to='bussiness.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.FloatField(default=1.0)),
                ('pago_elaboracion_monto', models.FloatField(default=1.0)),
                ('pago_elaboracion_relacion', models.CharField(max_length=1)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('cocinas', models.ManyToManyField(blank=True, null=True, related_name='cocinas_formula', to='kitchen.cocina')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoCocinaFormula', to='bussiness.producto')),
                ('subproducto', models.ManyToManyField(to='kitchen.cantidadsubproducto')),
                ('gastos', models.ManyToManyField(blank=True, null=True, to='kitchen.gastoselaboracion')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('monto', models.FloatField(default=0)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NotaCuadreCocina', to='kitchen.cuadre')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCocina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(default=0.0)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(blank=True, default=None, null=True)),
                ('transferido', models.BooleanField(default=False)),
                ('mensaje_cancelacion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('costo', models.FloatField(default=0.0)),
                ('cocina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocina_solicitada', to='kitchen.cocina')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_solicitado_cosina', to='bussiness.venta')),
            ],
        ),
        migrations.CreateModel(
            name='StockCocina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costo_produccion', models.FloatField(blank=True, null=True)),
                ('existencia', models.FloatField(blank=True, null=True)),
                ('cantidad_remitida', models.FloatField(blank=True, null=True)),
                ('cantidad_recibida', models.FloatField(blank=True, null=True)),
                ('cantidad_inicial', models.FloatField(blank=True, null=True)),
                ('cantidad_actual', models.FloatField(blank=True, null=True)),
                ('alta', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('consumo', models.TextField(blank=True, null=True)),
                ('cocina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CocinaStock', to='kitchen.cocina')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CocinaAlmacen', to='bussiness.stockalmacen')),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FormulaObjetivoCocinaStock', to='kitchen.formula')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductoCocinaStock', to='bussiness.producto')),
                ('transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cocinaTransferencia', to='bussiness.transferencia')),
                ('transformacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cocinaProductoTransformado', to='bussiness.formulatransformacion')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('monto', models.FloatField(default=0.0)),
                ('costo', models.FloatField(default=0.0)),
                ('costo_ext', models.FloatField(default=0.0)),
                ('ayudantes', models.ManyToManyField(blank=True, null=True, related_name='UserAyudanteCocina', to=settings.AUTH_USER_MODEL)),
                ('cocina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TurnoCocina', to='kitchen.cocina')),
                ('pagos', models.ManyToManyField(related_name='PagosTurnoCocina', to='bussiness.pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserTurnoCocina', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockProductoCompuestoCocina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consumo', models.TextField(blank=True, null=True)),
                ('costo_cup', models.FloatField(default=0.0)),
                ('cantidad_elaborada', models.FloatField(default=0.0)),
                ('cantidad_resultante', models.FloatField(default=0.0)),
                ('cantidad_actual', models.FloatField(default=0.0)),
                ('lote_auditable', models.BooleanField(blank=True, default=True, null=True)),
                ('fecha_fabricacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('monto_total', models.FloatField(default=0.0)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_compuesto_stock', to='bussiness.producto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_elaboracion_producto', to='kitchen.turno')),
            ],
        ),
        migrations.AddField(
            model_name='cuadre',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CuadreCocina', to='kitchen.turno'),
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(default=1.0)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidaProductoConsumido', to='bussiness.medida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoConsumido', to='bussiness.producto')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulaElaborada', to='kitchen.formula')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnoConsumo', to='kitchen.turno')),
            ],
        ),
    ]
