# Generated by Django 5.1.4 on 2025-03-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocina',
            name='categoria',
            field=models.CharField(choices=[('si', 'Elaboracion'), ('no', 'Venta')], default='si', max_length=12, verbose_name='Categoria_cocina'),
        ),
    ]
