# Generated by Django 5.1.4 on 2025-03-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CambiosAlmacen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('existencia', models.FloatField(blank=True, null=True)),
                ('cantidad', models.FloatField(default=0.0)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('monto', models.FloatField(default=0)),
                ('causa', models.TextField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ideal', models.FloatField(default=0.0)),
                ('alerta', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
