# Generated by Django 5.1.4 on 2025-03-17 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
        ('bussiness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cambiosalmacen',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bussiness.almacen', verbose_name='almacenCambiado'),
        ),
        migrations.AddField(
            model_name='cambiosalmacen',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoCambiado', to='bussiness.producto'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoPedido', to='bussiness.producto'),
        ),
        migrations.AddField(
            model_name='turno',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserTurnoAlmacen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nota',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NotaTurnoAlmacen', to='almacen.turno'),
        ),
    ]
