# Generated by Django 5.1.4 on 2025-03-22 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_initial'),
        ('bussiness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='TurnoAlmacen', to='bussiness.almacen'),
            preserve_default=False,
        ),
    ]
