# Generated by Django 5.1.4 on 2025-03-17 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bussiness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasaImpresion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('pago', models.FloatField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('duracion', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Fotografo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoEstado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('estados', models.ManyToManyField(to='estudio.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('contrato', models.BooleanField(default=True)),
                ('costo', models.FloatField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('moneda_precio', models.CharField(choices=[('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('CUP', 'Peso cubano'), ('MLC', 'Moneda libremente convertible')], max_length=3)),
                ('pago_fotografo', models.FloatField(default=0)),
                ('pago_responsable', models.FloatField(default=0)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudio.grupoestado')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioContrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0.0)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudio.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('precio', models.FloatField(default=0)),
                ('moneda_precio', models.CharField(choices=[('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('CUP', 'Peso cubano'), ('MLC', 'Moneda libremente convertible')], max_length=3)),
                ('anticipo', models.FloatField(default=0)),
                ('moneda_anticipo', models.CharField(choices=[('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('CUP', 'Peso cubano'), ('MLC', 'Moneda libremente convertible')], max_length=3)),
                ('pago_fotografo', models.FloatField(default=0)),
                ('pago_responsable', models.FloatField(default=0)),
                ('pago_gestor', models.FloatField(default=0)),
                ('monto_bolsa', models.FloatField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('servicios', models.ManyToManyField(to='estudio.serviciocontrato')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudio.tipocontrato')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioContratoCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('seleccion', models.TextField(blank=True, null=True)),
                ('fecha_acordada', models.DateTimeField(null=True)),
                ('terminado', models.BooleanField(default=False)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudio.estado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudio.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='FichaCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.CharField(max_length=200)),
                ('ci', models.CharField(max_length=200)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('entre', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('consejo_popular', models.CharField(blank=True, max_length=100, null=True)),
                ('muncp', models.CharField(blank=True, max_length=100, null=True)),
                ('prov', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('correo', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('telegram', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_contrata', models.CharField(blank=True, max_length=200, null=True)),
                ('ci_contrata', models.CharField(blank=True, max_length=200, null=True)),
                ('parentesco_contrata', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_contrata_2', models.CharField(blank=True, max_length=200, null=True)),
                ('ci_contrata_2', models.CharField(blank=True, max_length=200, null=True)),
                ('parentesco_contrata_2', models.CharField(blank=True, max_length=200, null=True)),
                ('autorizo_redes_sociales', models.BooleanField(default=True)),
                ('condiciones_publicacion', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_acordada', models.DateField(null=True)),
                ('fecha_seleccion', models.DateField(null=True)),
                ('fecha_realizacion', models.DateTimeField(null=True)),
                ('fecha_fin', models.DateField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('anotaciones', models.TextField(default='')),
                ('historial_cambios', models.JSONField(blank=True, null=True)),
                ('precio_contrato_cup', models.FloatField(default=0.0)),
                ('precio_contrato_usd', models.FloatField(default=0.0)),
                ('costo_cup', models.FloatField(default=0.0)),
                ('costo_usd', models.FloatField(default=0.0)),
                ('tasa_cambio_usd', models.FloatField(default=0.0)),
                ('audit', models.BooleanField(default=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_ficha', to='estudio.contrato')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_ficha', to='estudio.editor')),
                ('responsable_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_contrato_ficha', to=settings.AUTH_USER_MODEL)),
                ('responsable_revicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_revicion_ficha', to=settings.AUTH_USER_MODEL)),
                ('fotografo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografo_ficha', to='estudio.fotografo')),
                ('servicios_adicionales', models.ManyToManyField(related_name='servicios_adicionales_ficha', to='estudio.serviciocontratocliente')),
                ('servicios_contrato', models.ManyToManyField(related_name='servicios_contrato_ficha', to='estudio.serviciocontratocliente')),
            ],
        ),
        migrations.CreateModel(
            name='EnviosImpresion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lote', models.IntegerField()),
                ('fecha_envio', models.DateTimeField(null=True)),
                ('fecha_retorno', models.DateTimeField(null=True)),
                ('casa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casa_envio', to='estudio.casaimpresion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_envia_imprimir', to='estudio.serviciocontratocliente')),
            ],
        ),
        migrations.CreateModel(
            name='EnviosEdicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lote', models.IntegerField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_retorno', models.DateTimeField(null=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_envio', to='estudio.editor')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_envia_editar', to='estudio.serviciocontratocliente')),
            ],
        ),
        migrations.CreateModel(
            name='StockEstudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costo', models.FloatField(blank=True, null=True)),
                ('deuda', models.FloatField(blank=True, null=True)),
                ('existencia', models.FloatField(blank=True, null=True)),
                ('cantidad_remitida', models.FloatField(blank=True, null=True)),
                ('cantidad_recibida', models.FloatField(blank=True, null=True)),
                ('cantidad_inicial', models.FloatField(blank=True, null=True)),
                ('cantidad_actual', models.FloatField(blank=True, null=True)),
                ('alta', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LoteStockSalon', to='bussiness.stockalmacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductoStockEstudio', to='bussiness.producto')),
                ('transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TransferenciaEstudio', to='bussiness.transferencia')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuadre', models.JSONField()),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserTurnoEstudio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
