# Generated by Django 5.1.4 on 2025-03-17 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bussiness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('monto', models.FloatField(default=0.0)),
                ('moneda', models.CharField(choices=[('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('CUP', 'Peso cubano'), ('MLC', 'Moneda libremente convertible')], default='CUP', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('centro_costo', models.CharField(max_length=50)),
                ('monto', models.FloatField(default=0.0)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CapitalLiquides',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capital', models.FloatField(default=0.0)),
                ('liquides', models.FloatField(default=0.0)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoMensual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('centro_costo', models.CharField(max_length=50)),
                ('motivo', models.CharField(max_length=500)),
                ('monto', models.FloatField(default=0.0)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReciboEfectivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.TextField(blank=True, null=True)),
                ('recibido', models.TextField(blank=True, null=True)),
                ('monto', models.FloatField(default=0.0)),
                ('monto_letra', models.TextField(blank=True, null=True)),
                ('motivo_diferencia', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomina', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user_confirm', models.CharField(blank=True, max_length=200, null=True)),
                ('descuentos', models.ManyToManyField(blank=True, null=True, to='bussiness.descuentos')),
                ('pagos', models.ManyToManyField(blank=True, null=True, to='bussiness.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField(default=0.0)),
                ('motivo', models.TextField()),
                ('existencia', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.caja')),
            ],
        ),
    ]
