# Generated by Django 5.1.4 on 2025-03-17 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bussiness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CantidadSubproducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(default=0.0)),
                ('subgrupo', models.CharField(blank=True, max_length=5, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CantidadSubproductoSalon', to='bussiness.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('precio_usd', models.FloatField(default=0.0)),
                ('descuento', models.FloatField(default=0.0)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('pago_monto', models.FloatField(default=1.0)),
                ('pago_relacion', models.CharField(max_length=1)),
                ('activo', models.BooleanField(default=True)),
                ('subproductos', models.ManyToManyField(to='salon.cantidadsubproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('ci', models.CharField(blank=True, max_length=11, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('user_id', models.CharField(max_length=999)),
                ('user_name', models.CharField(max_length=999)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_acordada', models.DateTimeField(null=True)),
                ('fecha_realizacion', models.DateTimeField(null=True)),
                ('costo', models.FloatField(default=0.0)),
                ('razon_cambio', models.FloatField(default=0.0)),
                ('monto_base', models.FloatField(default=0.0)),
                ('monto_cobrado', models.FloatField(default=0.0)),
                ('moneda', models.CharField(choices=[('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('CUP', 'Peso cubano'), ('MLC', 'Moneda libremente convertible')], default='CUP', max_length=3)),
                ('contrato_id', models.IntegerField(blank=True, null=True)),
                ('audit', models.BooleanField(default=True)),
                ('pagos', models.ManyToManyField(blank=True, null=True, to='bussiness.pago')),
                ('servicios', models.ManyToManyField(related_name='servicios_cliente_salon', to='salon.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuadre', models.JSONField()),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserTurnoSalon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_name', models.CharField(max_length=999)),
                ('servicio', models.CharField(max_length=999)),
                ('cantidad', models.FloatField(default=1.0)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ClienteConsumo', to='salon.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoConsumidoSalon', to='bussiness.producto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnoConsumidoSalon', to='salon.turno')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnoClienteSalon', to='salon.turno'),
        ),
    ]
